import { NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getMessages } from "next-intl/server";
import StoreProvider from "./StoreProvider";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import BackToTopBtn from "@/components/Buttons/BackToTopBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <StoreProvider>
        <html lang={locale}>
          <body className={`bg-white ${inter.className}`}>
            <Header />
            <main>{children}</main>
            <Footer />
            <BackToTopBtn />
          </body>
        </html>
      </StoreProvider>
    </NextIntlClientProvider>
  );
}
