import { NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useMessages } from "next-intl";
import StoreProvider from "./StoreProvider";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  const messages = useMessages();

  return (
    <NextIntlClientProvider messages={messages} locale={locale}>
      <StoreProvider>
        <html lang={locale}>
          <body className={inter.className}>
            <Header />
            <main>{children}</main>
            <Footer />
          </body>
        </html>
      </StoreProvider>
    </NextIntlClientProvider>
  );
}
